version: '3.7'
services:
    mongo:
        image: 'mongo'
        container_name: 'mongo-services'
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
        volumes:
            - ./db:/data/db
        ports:
            - '27017-27019:27017-27019'
        networks: 
            - mongo_network
    backend:
        build:
            context: ./server
            args:
                workDir: /usr/local/app
                MONGO_URI: ${MONGO_URI}
                PORT: ${PORT}
        container_name: 'cpm-services'
        ports: 
            - ${PORT}:${PORT}
        networks: 
            - mongo_network
            - backend_network
    frontend:
        build: 
            context: ./client
        container_name: 'cpm-webapp'
        networks: 
            - backend_network
networks: 
    mongo_network:
    backend_network: